spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql://localhost:3306/blog?createDatabaseIfNotExist=true
    username: ${BLOG_DB_USER}
    password: ${BLOG_DB_PASS}
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  jwt:
    secret: ${JWT_SECRET}